### ISSUE TITLE
Check Fluent Icons into codebase instead of pulling from `node_modules`

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#132]
# Summary

As a developer, I do not want InKind's icons to break with a dependency upgrade.

## Things to Consider

The Fluent icons in the sidebar looks and work great! But the svgs are getting pulled from `node_modules/*`, which means if the fluent library decides to move their icons around, they won't render in the app anymore.

This is easy to fix! We should check the `svg`s directly into the codebase so there is no chance they could move directories and break the nav in the future.

# Criteria for Completion
 - [ ] Icons are checked into the repo and linked directly from the codebase.
 - [ ] Sidebar nav looks and works the same.

**Comment by RudeChowder** [comment]
@Jelenad1 and I can take this one on

**Comment by JelenaD1** [comment]
@RudeChowder and I are pairing on this one.
