### ISSUE TITLE
Standardize Date representations

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#133]
# Summary

As a admin, I want a consistent representation of dates.

## Things to Consider

There are a few different representations of dates in the application right now. Let's unify them to only one format for consistency.

# Criteria for Completion
 - [ ] All dates represented in the user interface should display in the American format of "MM/DD/YYYY" (e.g. 06/27/1964)

**Comment by roman-rezinkin** [comment]
I am having a lot of issues with setup, so unfortunately I cannot contribute to help fix the format of the dates. I am not sure if it is because I am on Windows 10, but I have been trying to deploy the front end and backend for a few days with no success. Sorry.

**Comment by garettarrowood** [comment]
Sorry to hear you are having trouble, @roman-rezinkin . If you have any error output, feel free to drop it into an issue and hopefully I or someone else can try to find a solution.
