### ISSUE TITLE
Students have many active volunteers

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#143]
# Summary

After meeting with the stakeholders again, we've discovered that some students have many active volunteers at one time. The student_volunteer_assignment logic needs to be updated to account for this

## Things to Consider

This product is still pre-MVP. 

# Criteria for Completion
 - [ ] When adding/updating a student, multiple active volunteers can be assigned
 - [ ] When the form is saved, current assigned volunteers stay assigned UNLESS they've been removed.
 - [ ] When the form is save, additional volunteers will be assigned to the student AND active. (validation to only have one assigned volunteer must change)

What student form looks like now:

![Screen Shot 2021-11-20 at 10 20 26 AM](https://user-images.githubusercontent.com/12770108/142731817-846ab3f0-5305-4b4b-bb62-f785c9a562b3.png)

What we eventually would like it to work/look like:

![Screen Shot 2021-11-20 at 10 18 17 AM](https://user-images.githubusercontent.com/12770108/142731830-903c19a2-bf55-4653-ae26-7a05423a97f7.png)

This story does not need to accomplish everything. But the ultimate goal is to have a typeahead input. And when the end-user clicks on a volunteer name, it is added to the list below. In the list below, a volunteer can be removed by clicking the X next to there name.

This story is acceptable when any functionality exists on this form that allows for multiple volunteer assignment.

Questions? - find us on Slack :).

**Comment by goromlagche** [comment]
Hi @garettarrowood I would like to work on this. Is it possible for you to assign this issue to me? Thank you!

**Comment by goromlagche** [comment]
Hi @garettarrowood, I have one confusion with this statement 

```
When the form is saved, current assigned volunteers stay assigned UNLESS they've been removed.
```

My confusion is, does this spec https://github.com/rubyforgood/inkind-admin/blob/main/spec/requests/students_spec.rb#L75-L84 still holds true with the above statement?

**Comment by garettarrowood** [comment]
Yes, that spec does hold true!

I would guess that every time the student form is saved, it sends down all relevant active volunteers assigned to that student. So if none are there, it would mark all the previously assigned volunteers to inactive.
