### ISSUE TITLE
Sort Volunteers by status

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#144]
# Summary

Sort volunteers by there status, the same way sorting works for first and last name

## Things to Consider

 This project is pre-MVP.

# Criteria for Completion
 - [ ] Clicking on the "Status" header on the Volunteer index page sorts the statuses. Clicking again sorts the other way. 

Page as it looks now, with last name sorted:

![Screen Shot 2021-11-20 at 10 33 04 AM](https://user-images.githubusercontent.com/12770108/142732117-5ec9ba60-80c3-433f-b7b1-4e7727f7cb63.png)

**Comment by goromlagche** [comment]
Hi @garettarrowood I would like to work on this. Is it possible for you to assign this issue to me. Thank you!
