### ISSUE TITLE
Split Guardian & Emergency Contact name fields on Student

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#145]
# Summary

Currently there is a `guardian_name` and `emergency_contact_name` field on the student Model/table. These need to be split into `guardian_first_name`, `guardian_last_name`, `emergency_contact_first_name`, & `emergency_contact_last_name`. 

## Current student schema

```ruby
  create_table "students", force: :cascade do |t|
    t.string "first_name", null: false
    t.string "last_name", null: false
    t.string "email"
    t.string "phone_number"
    t.integer "status", default: 0, null: false
    t.string "guardian_name"
    t.string "guardian_phone_number"
    t.string "emergency_contact_name"
    t.string "emergency_contact_phone_number"
    t.date "date_of_birth"
    t.datetime "deactivated_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.bigint "deactivator_id"
    t.index ["deactivator_id"], name: "index_students_on_deactivator_id"
  end
```

## Things to Consider

This product is still pre-MVP. So don't worry about backwards compatibility data. There is no prod db yet.

# Criteria for Completion
 - [ ] Specified name fields are removed and replaced with first/last name fields
 - [ ] Update the seed files to still create valid students
 - [ ] Update the Students index so it doesn't break. Guardian last name is fine, feel free to add both.
 - [ ] Update the Student form to accept inputs for these fields as shown in mock below.

HOW IT LOOKS NOW:

![Screen Shot 2021-11-20 at 10 41 03 AM](https://user-images.githubusercontent.com/12770108/142732373-48991a35-b612-4552-9221-622b1ad87ee1.png)

How it should generally look after this change:

![Screen Shot 2021-11-20 at 10 41 17 AM](https://user-images.githubusercontent.com/12770108/142732385-c47967cb-c051-47c9-944a-2d461bee3f61.png)

**Comment by JelenaD1** [comment]
I'll work on this issue.
