### ISSUE TITLE
Sorting on `Admin` page

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#146]
# Summary

Add sorting by name and status to the Admin index page, in the same way that sorting is applied on Students/Volunteers index pages.

ALSO - The admin (`users`) name is stored as first and last name. Update the index page to have a column for each of these, and allow for sorting on either (same as volunteers). 

# Criteria for Completion
 - [ ] Admin first name is sortable by clicking on the table header
 - [ ] Admin last name is sortable by clicking on the table header
 - [ ] Admin status is sortable by clicking on the table header

This is how sorting looks on the Volunteers page:

![Screen Shot 2021-11-20 at 10 33 04 AM](https://user-images.githubusercontent.com/12770108/142732618-6d958c2d-f70a-4511-a3e2-a752b0136e05.png)

This is how the Admins page looks now:

![Screen Shot 2021-11-20 at 10 46 28 AM](https://user-images.githubusercontent.com/12770108/142732629-6f5c2480-1fc6-4b53-bf30-e8c122607d32.png)

**Comment by goromlagche** [comment]
Hi @garettarrowood I would like to work on this. Is it possible for you to assign this issue to me?
