### ISSUE TITLE
Styled De/activation Confirmations (JS Alerts)

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#155]
# Summary

When deactivating a volunteer/student/admin, the default browser JS alert confirms the user's action. These alerts should be in the style of InKind UX/UI.

# Criteria for Completion
 - [ ] Current functionality remains intact. Activating & deactivating a student/volunteer/admin pops a confirmation alert.
 - [ ] The new alert matches the provided mockup

## What the alert looks like now (or whatever your specific browser does):

<img width="506" alt="Screen Shot 2021-11-28 at 1 07 01 PM" src="https://user-images.githubusercontent.com/12770108/143780447-cf12e5df-d685-4c2d-b150-7ebda82ff8a0.png">

## How the alert should look after this change:

![Screen Shot 2021-11-28 at 1 06 24 PM](https://user-images.githubusercontent.com/12770108/143780465-c7a09a17-7f7c-4f8c-b53b-1032dc230819.png)

**Comment by JelenaD1** [comment]
Hey @garettarrowood , there's a SweetAlert gem that will fix this issue. t's Awesome, and you will get lots of customization option as well as all callbacks: https://github.com/t4t5/sweetalert

I can tackle this one as well.

**Comment by garettarrowood** [comment]
I'm familiar with SweetAlert and it does look like it might be the right tool for the job here. The only thing I don't like about that repo is that it hasn't been updated in 2.5 years (looks unmaintained), with quite a lot of open issues and PRs.

But the alternatives look even less maintained.  https://github.com/nicolasblanco/sweet-alert2-rails .

I'm wondering how easy that library is to customize with style as well...

With that said, do feel free to give this a shot with [SweetAlert](https://github.com/t4t5/sweetalert).
