### ISSUE TITLE
Revamp the Support Ticket Index page

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#156]
# Summary

Our current Support Ticket page represents the first pass at this view. It needs new/changed columns, sortability, and revamped styling.

# Criteria for Completion
 - [ ] Headers on page match the header names in the mockup (in the right order)
 - [ ] Correct data shows up for each column
 - [ ] Standard sorting (follow conventions of Volunteers page) are added to the "Requested By", "Date Created", "Student" (sort on last name), "Staff Contact" (sort on last name), and "Type" . If some sorting seems too hard to get done in this deliverable, it can be moved into another issue.
 - [ ] Nav item STAYS "Tickets", but page title is updated to "Support Tickets"
 - [ ] (No need to implement any filtering yet. That feature will come in another issue.)

### What does each column represent?

- "Requested By:" is what is currently showing up as the "Requestor"
- "Date Created" is what is currently showing up as "Created At"
- "Response ID" is the `survey_response_id` on the support_ticket. These only exist on "Support" Type tickets. There is no need to make this a link yet, just the ID is fine.
- "Student" is the student associated with the related `survey_response`. These only exist on "Support" Type tickets as well. If there is no `survey_response` on the ticket, this field will be left blank.
- "Staff Contact" is the name of the active staff contact associated with the student (for "Support" type tickets). If the requestor IS an admin, the staff contact shows the admin name again (admin == staff). If it's a "Contact" type, drop in the name(s) of the volunteer's students' active staff contact. This will likely only be one name, but could be more that one.
- "Type" is the support ticket category. `survey_response` => "Support". `admin` => "Admin", `contact_info` => "Contact".
- "Action" is the status, but also the link to the resolve form. So where there is a "View" link now, it may become a "Resolve" link that goes to the same place. Or a "Closed" link that also goes to the same place.

## How it looks now:

<img width="1180" alt="Screen Shot 2021-11-28 at 1 35 13 PM" src="https://user-images.githubusercontent.com/12770108/143781359-08be0223-dd23-49db-9171-e8d1303a0947.png">

## How it will look after this update

(Disregard the filter input - and disregard the different table style.) Also, we will not be adding an import button to this view.

![Screen Shot 2021-11-28 at 1 14 56 PM](https://user-images.githubusercontent.com/12770108/143781371-c31324c0-5443-4b6f-9d08-9c5d0a64d63f.png)

**Comment by goromlagche** [comment]
Hello @garettarrowood , I would like to work on this.


> disregard the different table style

By this, do you mean the change in CSS in the new screenshot?

**Comment by garettarrowood** [comment]
@goromlagche - Essentially, yes. 

This style:
<img width="418" alt="Screen Shot 2021-12-05 at 8 54 19 AM" src="https://user-images.githubusercontent.com/12770108/144749533-ede9c437-1e5f-4b40-a8c1-a6ea9930dde0.png">

Does not yet need to change to this style:
<img width="404" alt="Screen Shot 2021-12-05 at 8 54 26 AM" src="https://user-images.githubusercontent.com/12770108/144749540-2f2e1ac4-7127-4f3a-811b-2aae6734d71c.png">

Because when we do so, it would be good to updated the table style of all 4-5 views at once instead of making one look different than the rest.
