### ISSUE TITLE
Resolving Support Ticket Form

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#157]
# Summary

The support ticket resolution form needs to save "closer_notes" and be updated to match InKind styling (the mockup).

# Criteria for Completion
 - [ ] Clicking "Cancel" in this form redirects the user back to the Tickets index page (currently broken)
 - [ ] Clicking "Resolve" in this form saves the notes left by the reviewer/resolver & updates the `support_ticket`'s `closed_at` & `closer_id` fields.
 - [ ] The new form looks like the attached form mockup.
 - [ ] When clicking to view a "closed" support ticket, the view matches the 2nd attached mockup.

## What it looks like now:

<img width="894" alt="Screen Shot 2021-11-28 at 1 59 36 PM" src="https://user-images.githubusercontent.com/12770108/143782214-7e1d8e1d-dbb0-4e7e-958b-bed2000e5d90.png">

## What an unresolved (open) support_ticket form will look like after this change:

Notes: 

- "Created By" volunteer should not be a link. Just regular text.
- The "Support Request" text under the requestor's name should be dynamic. It should be something like`"#{category} Request", where category is the `support_ticket.category`. Where `survey_response` => "Support", `admin` => "Admin", and `contact_info` => "Contact".
- "Student" is the student associated with the related survey_response. These only exist on "Support" Type tickets as well. If there is no survey_response on the ticket, this field will be left blank.
- "Staff Contact" is the name of the active staff contact associated with the student (for "Support" type tickets). If the requestor IS an admin, the staff contact shows the admin name again (admin == staff). If it's a "Contact" type, drop in the name(s) of the volunteer's students' active staff contact. This will likely only be one name, but could be more that one.

![Screen Shot 2021-11-28 at 2 00 11 PM](https://user-images.githubusercontent.com/12770108/143782226-da7b856e-4ec0-4215-8671-8ac16ac30dde.png)

## What a resolved (closed) support_ticket will look like after this change:

Notes:

"View Tickets" button just links back to the support_tickets index.

![Screen Shot 2021-11-28 at 2 00 24 PM](https://user-images.githubusercontent.com/12770108/143782233-a1d17427-7fc6-4727-8c0a-6431ca7b574e.png)

**Comment by goromlagche** [comment]
Hello @garettarrowood , I would like to work on this. Is it possible to assign this ticket to me? Thank you!
