### ISSUE TITLE
Update Organization Form

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#160]
# Summary

Update the styles on the Organization form to match the mockup.

## Things to Consider

The student form has the most up-to-date-ish styling so far. Feel free to reference that to align conventions.

# Criteria for Completion
 - [ ] Organization form looks like the attached mockup
 - [ ] The form still works, saving all fields.

## How it looks now:

<img width="864" alt="Screen Shot 2021-11-28 at 4 18 48 PM" src="https://user-images.githubusercontent.com/12770108/143786460-e0a320a9-cb93-43d0-b555-78038e3dc44f.png">

## How it will look after this change:

Note: Keep City/State easy. They should be two separate inputs, as they are stored on the table.

![Screen Shot 2021-11-28 at 4 18 09 PM](https://user-images.githubusercontent.com/12770108/143788815-48fba8aa-23a8-45a5-8546-a34fa3359550.png)

**Comment by Ashvith** [comment]
@garettarrowood just my opinion, but I feel like the *Information* label is not really needed, as the heading is pretty much self-explanatory. What do you think?

**Comment by garettarrowood** [comment]
@Ashvith - Agreed. -- The design for all of the forms in this app have that "Information" label at the top. We'll either not do it anywhere, or the designer will convince me it has value and one PR can add it across the board. -- In this issue, please leave it out :).

**Comment by Ashvith** [comment]
@garettarrowood what about the **Phone Number** text box? It is not present in the page originally. Should I just provide a dummy text input?

**Comment by garettarrowood** [comment]
Back and Cancel are the same, yes.

Leave the Phone Number off. We can add it if it's ever needed (which I don't think it ever will be).

Should I assign this one to you?

**Comment by Ashvith** [comment]
@garettarrowood I am not experienced enough to join the two input text box into a single drop-down text box. Maybe we can open another issue for the same?

**Comment by garettarrowood** [comment]
@Ashvith - For sure - I don't think we will ever do that actually. See my comments on your PR, just a couple more changes and things look good to go.
