### ISSUE TITLE
Update Student Export

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#164]
# Summary

Right now, this export only ships with 4 columns. Here are the columns/headers this export should support:

- First Name
- Last Name
- Volunteer Name(s)
- Staff Contact
- DOB
- Guardian First Name
- Guardian Last Name
- Guardian Phone
- Guardian Email 
- Emergency Contact First Name
- Emergency Contact Last Name
- Emergency Contact Phone
- Hours logged (Minutes logged is fine, like the Volunteer export)
- Number of sessions
- City
- State

## Things to Consider

The volunteer export.

Check out how it finds active Student/Volunteer/Staff assignments. How it sums minutes logged. And how it determines the number of sessions.

# Criteria for Completion
 - [ ] Export works and contains the headers above with the correct values
 - [ ] Automated test covering enhancement

**Comment by garettarrowood** [comment]
Currently blocked by #145

**Comment by goromlagche** [comment]
Hello @garettarrowood , I would like to work on this. Is it possible to assign this ticket to me? Thank you!

**Comment by goromlagche** [comment]
I could not find a `Guardian Email` field :thinking: 

Is this needs to be added?

**Comment by garettarrowood** [comment]
@goromlagche - Yes, I believe so. Feel free to leave it off for now, OR, feel free to add the column and add an input on the student form.
