### ISSUE TITLE
Add filters to the volunteer page table

### ISSUE THREAD

**Issue by sowmi20189** [rubyforgood/inkind-admin#179]
# Summary

As an admin, I would like to see the option to filter the volunteer page table menu so that I can analyze the data better.

## Things to Consider
Please use the StimulusReflex framework we've embraced for all of our sorting (it's a tool that is built for this).

# Criteria for Completion

 - [ ] Add filters to the following fields: First Name, Last Name, Staff Contact, and Status
 - [ ] The table must display the results of the selected filter across the fields
 - [ ] One or more filters can be used at a time

**Comment by goromlagche** [comment]
Hello @garettarrowood , I would like to work on this. Is it possible to assign this ticket to me? Thank you!

**Comment by garettarrowood** [comment]
Awesome! Thank you!
