### ISSUE TITLE
Edit Volunteer with existing students and staff 

### ISSUE THREAD

**Issue by sowmi20189** [rubyforgood/inkind-admin#191]
# Summary

As an admin, I would like to edit the existing volunteer details for whom students and staff contact are assigned.

# Criteria for Completion
 - [ ] Be able to edit the first name, last name, email, and phone number
 - [ ] Remove existing student contact by highlighting on the name and clicking on the 'x' mark at the right end
 - [ ] Add new/more students associated to the volunteer
 - [ ] Similarly remove/add existing staff contact
 - [ ] Rename the submit button as Save by following the design guidelines 

Refer screenshot:

<img width="649" alt="Edit volunteer" src="https://user-images.githubusercontent.com/96266018/149840271-5446b925-2f10-40a2-b898-7c2a3c568023.png">

**Comment by garettarrowood** [comment]
Students make sense. But staff we need to be figured out because the only way a volunteer has staff is through the student.

**Comment by garettarrowood** [comment]
I updated #190 to embody both creating and updating. This functionality uses the same form under the hood.

And based on my comment above and our chat on Slack, I've removed the Staff portion of this for now and limited the issue to adding the student assignment, and updating the styling.
