### ISSUE TITLE
Trouble Updating to Ruby 3.0.2 with asdf --> SOLVED!

### ISSUE THREAD

**Issue by meg-gutshall** [rubyforgood/inkind-admin#51]
# Summary

This is primarily an add for documentation. I would add it to the Wiki but I don't have the appropriate permissions.

## Issue

I had some issues updating to Ruby 3.0.2 using asdf as my Ruby version manager.

When writing in the command `asdf list all ruby`, 3.0.2 was not included and 3.0.1 was returned when I wrote `asdf latest ruby`.

## Solution

I found [a resource online](https://cloudolife.com/2021/07/10/Programming-Language/Ruby/Ruby-3-0-2-Released/) that suggested running `asdf plugin update ruby` in the terminal. After that I was able to run `asdf install ruby 3.0.2` with no problem! I navigated to my local copy of the repo and after typing `ruby -v` received back the correct 3.0.2 version.

I hope this helps anyone else how gets stuck here!

**Comment by meg-gutshall** [comment]
FYI @garettarrowood

**Comment by garettarrowood** [comment]
I'll investigate tomorrow and see if I have the ability to change your access rights with the Wiki pages.
