### ISSUE TITLE
Add Volunteer Import modal

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#54]
# Summary

As an admin, I'd like a know how to import volunteers into InKind

## Things to Consider

This project is a Ruby for Good project. That means it should use conventions from other Ruby for Good projects (instead of inventing a comparable, but different solution). This allows for easy cross-project contributions and knowledge sharing. Please reference https://github.com/rubyforgood/human-essentials & https://github.com/rubyforgood/casa when crafting this work.

This story in particular should follow conventions used in the repos above, as they have identical functionality.

Blocked by #33 

# Criteria for Completion
 - [ ] While on the Volunteer Index page, clicking on a new "Import" button prompts a modal with instructions
 - [ ] Within modal, copy and format should match mockup
 - [ ] Create disabled/placeholder buttons with the modal for now
 - [ ] Add test coverage if applicable

<img width="743" alt="Screen Shot 2021-10-12 at 2 03 55 PM" src="https://user-images.githubusercontent.com/12770108/137006954-546d7844-90a0-4570-8a43-d15a06d15262.png">

### Bonus

- [ ] Make the "Download sample CSV" button work. Sample CSV should have headers that match name of fields in `users` table. Should have a few sample rows (see what CASA/human-essentials does)

### Extra Details

Q: What does the "Mock Update Pending" tag mean?

A: This issue contains a mockup that is good enough to complete the work. But more detailed mocks are in progress. When the final mockup is complete, this issue will be updated, and the tag removed. (If you do not see the "Mock Update Pending" tag, the mockup is potentially final.)

**Comment by rimenes** [comment]
I'm on it
