### ISSUE TITLE
Download Sample CSV File

### ISSUE THREAD

**Issue by marquesavery** [rubyforgood/inkind-admin#59]
# Summary

A user can download an example csv file 

## Things to Consider

This project is a Ruby for Good project. That means it should use conventions from other Ruby for Good projects (instead of inventing a comparable, but different solution). This allows for easy cross-project contributions and knowledge sharing. Please reference https://github.com/rubyforgood/human-essentials & https://github.com/rubyforgood/casa when crafting this work.

Blocked by #61 & #54 

# Criteria for Completion

 - [ ] When a user clicks the Import button on the Volunteers and Students page they see a model that has a Download sample csv file.
 - [ ] Clicking the "Download sample csv" will download an example CSV file

![Screen Shot 2021-10-12 at 4 18 21 PM](https://user-images.githubusercontent.com/65418438/137023324-1206985f-2fa9-4cda-95fc-c2ea2c334715.png)

**Comment by rodolfoasantos** [comment]
@garettarrowood  Do you mind to assign this one to @rimenes? He is going to accomplish this one as part of #61

**Comment by garettarrowood** [comment]
This one is done!
