### ISSUE TITLE
Deactivate & activate Volunteers/Admins

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#75]
# Summary

As an admin, I would like to deactivate and activate volunteers and admins.

# Criteria for Completion
 - [ ] From the Admin and Volunteer index pages, add an action to "Deactivate" if the user is active. Upon clicking the action, pop a confirmation modal before deactivating the user.
 - [ ] When a user deactivates, update their `deactivated_at`, change their `status` to inactive, and add a column for `deactivator_id` that references the current user who executed the action (and update it).
 - [ ] From the Admin and Volunteer index pages, add an action to "Activate" if the user is inactive. Upon clicking the action, pop a confirmation modal before activating the user.
 - [ ] When a user activates, change their `status` to active.

**Comment by kellyeryan** [comment]
Whoever takes this, I am working on #74 - https://github.com/rubyforgood/inkind-admin/issues/74 - it is quite similar, so perhaps we could sync and make sure we are coordinating our approaches.

**Comment by rimenes** [comment]
I'm on it
