### ISSUE TITLE
Style the TopNav and SidebarNav

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/inkind-admin#89]
# Summary

As an admin, I would like the layout of InKind to look good.

## Things to Consider

This PR embodies updating the colors/fonts/icons/proportions for the layout of this application. Not the styles in the main body of the page (from the mockup).

Dark purple color in top nav bar is: #311B92
Light purple color for a selected item in the sidebar is: #EDE7F6
If you have trouble finding/getting the exact icons, reach out for help in the #team-inkind Slack channel.

There are no notifications yet, so leave off the bell icon in top right corner for now.
The hamburger dropdown icon is in there, and pops when the page shortens to ipad/mobile size. But it's black and hard to see. And clicking it reveals the avatar link instead of the sidebar links. Fixing this is a bonus, but not a hard requirement that prevents other styling improvements from shipping first.

# Criteria for Completion
 - [ ] Colors and sizing matches the attached mockup
 - [ ] Icons in the sidebar nav match the mockup (these are Fluent icons)
 - [ ] Change "Dashboard" nav title to "Home" (only Home, Volunteers, Students, Admins & Tickets exist so far)

<img width="730" alt="Screen Shot 2021-10-14 at 9 23 46 PM" src="https://user-images.githubusercontent.com/12770108/137417764-6d4869f3-37c3-4585-8efb-ffabb56acea1.png">

**Comment by Ashvith** [comment]
Can I have a look at this issue?

**Comment by garettarrowood** [comment]
<img width="733" alt="Screen Shot 2021-10-19 at 8 55 36 PM" src="https://user-images.githubusercontent.com/12770108/138010382-8e85cdf5-7f3b-4ed2-82e3-cb89ba1cc14c.png">

Here's a slightly newer version. Looks like a some small difference that the "Built with Love by Ruby for Good" is now in the left nav (it should be there already). And when a nav item is clicked, the text & icon becomes a darker purple.

Feel free to give this a shot. But also know there's no need to get everything done in one pass. Since this project is still pre-MVP, I'm looking to merge anything that represents a step in the right direction.
